version: '3.6'
services:
  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - '80:80'
      - '443:443'
    volumes:
      - ./client/config/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./client/config/certs:/etc/letsencrypt
      - ./client/config/certs-data:/data/letsencrypt
      - ./client/wordpress:/var/www/html
      - ./logs/nginx:/var/log/nginx
    links:
      - wordpress
    restart: always

  mysql:
    image: mariadb
    container_name: mysql
    volumes:
      - ./mysql:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=password
    restart: always

  wordpress:
    image: wordpress:php7.2-fpm
    container_name: wordpress
    volumes:
      - ./client/wordpress:/var/www/html
      - ./client/config/php/php.ini:/usr/local/etc/php/php.ini
    environment:
      - WORDPRESS_DB_NAME=wordpress
      - WORDPRESS_TABLE_PREFIX=wp_
      - WORDPRESS_DB_HOST=mysql
      - WORDPRESS_DB_PASSWORD=password
    links:
      - mysql
    restart: always